n = int(input("Digite o valor do número: "))
dobro = (n*2)
triplo = (n*3)
raiz = n ** (1/2)
print ("O dobro do número {} é {}".format(n, dobro))
print ("O triplo do número {} é {}".format(n, triplo))
print ("A raiz do número {} é {}".format(n, raiz))
